
// This file has been generated by the GUI designer. Do not modify.
namespace DigitalWatch.Displays
{
	public partial class BinaryDisplayWidget
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label DisplayHoursLabel;
		
		private global::Gtk.Label DisplayMinutesLabel;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button PrimaryButton;
		
		private global::Gtk.Button SecondaryButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DigitalWatch.Displays.BinaryDisplayWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DigitalWatch.Displays.BinaryDisplayWidget";
			// Container child DigitalWatch.Displays.BinaryDisplayWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.DisplayHoursLabel = new global::Gtk.Label ();
			this.DisplayHoursLabel.Name = "DisplayHoursLabel";
			this.DisplayHoursLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.vbox1.Add (this.DisplayHoursLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.DisplayHoursLabel]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.DisplayMinutesLabel = new global::Gtk.Label ();
			this.DisplayMinutesLabel.Name = "DisplayMinutesLabel";
			this.DisplayMinutesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
			this.vbox1.Add (this.DisplayMinutesLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.DisplayMinutesLabel]));
			w2.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.PrimaryButton = new global::Gtk.Button ();
			this.PrimaryButton.CanFocus = true;
			this.PrimaryButton.Name = "PrimaryButton";
			this.PrimaryButton.UseUnderline = true;
			this.PrimaryButton.Label = global::Mono.Unix.Catalog.GetString ("Primary");
			this.hbox1.Add (this.PrimaryButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PrimaryButton]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.SecondaryButton = new global::Gtk.Button ();
			this.SecondaryButton.CanFocus = true;
			this.SecondaryButton.Name = "SecondaryButton";
			this.SecondaryButton.UseUnderline = true;
			this.SecondaryButton.Label = global::Mono.Unix.Catalog.GetString ("Secondary");
			this.hbox1.Add (this.SecondaryButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.SecondaryButton]));
			w4.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.PrimaryButton.Clicked += new global::System.EventHandler (this.OnPrimaryButtonClicked);
			this.SecondaryButton.Clicked += new global::System.EventHandler (this.OnSecondaryButtonClicked);
		}
	}
}
