
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox2;
	
	private global::DigitalWatch.Displays.LCDDisplayWidget lcddisplaywidget1;
	
	private global::DigitalWatch.Displays.SegmentDisplayWidget segmentdisplaywidget2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lcddisplaywidget1 = new global::DigitalWatch.Displays.LCDDisplayWidget ();
		this.lcddisplaywidget1.Events = ((global::Gdk.EventMask)(256));
		this.lcddisplaywidget1.Name = "lcddisplaywidget1";
		this.hbox2.Add (this.lcddisplaywidget1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lcddisplaywidget1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.segmentdisplaywidget2 = new global::DigitalWatch.Displays.SegmentDisplayWidget ();
		this.segmentdisplaywidget2.Events = ((global::Gdk.EventMask)(256));
		this.segmentdisplaywidget2.Name = "segmentdisplaywidget2";
		this.hbox2.Add (this.segmentdisplaywidget2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.segmentdisplaywidget2]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.hbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 624;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
